### ISSUE TITLE
LinkedIn connection not working

### ISSUE THREAD

**Issue by Su-nlight** [shreyasingh2003/shreyasingh2003#2]
1.  There is an error in line number 35 of `README.md` file...

Instead of 
`<a href="https://linkedin.com/in/https://www.linkedin.com/in/shreya-singh2025" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="https://www.linkedin.com/in/shreya-singh2025" height="30" width="40" /></a>`
It should be 
`<a href="https://www.linkedin.com/in/shreya-singh2025" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="https://www.linkedin.com/in/shreya-singh2025" height="30" width="40" /></a>`

2.  There is one more error in line 39 of same file as mentioned above, 
Instead of phrase
`<a href="https://discord.gg/Shreya singh#1782" target="blank">`
it should be 
`<a href="https://discord.com/users/932272580579188757" target="blank">`

Though these are minor errors still I thought of raising these.

**Comment by shreyasingh2003** [comment]
Thank you
